# Generated by Django 5.2.11 on 2026-03-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='activities_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='flight_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='food_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='from_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='source_external_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='taxi_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='to_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='vibe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(default='luxury', max_length=50),
        ),
    ]
