# Generated by Django 5.2.11 on 2026-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_activities_cost_package_flight_cost_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category'], name='packages_pa_categor_ffec45_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['vibe'], name='packages_pa_vibe_3425f8_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['price'], name='packages_pa_price_3806c5_idx'),
        ),
    ]
