# Generated by Django 5.2.11 on 2026-03-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.booking',),
        ),
    ]
